
server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  spring.session.store-type: none


spring:
  # 数据库配置
  datasource:
#    url: jdbc:jtds:sqlserver://192.168.3.135:1433/方臣2007
    url: jdbc:jtds:sqlserver://localhost:1435/方臣2007
    username: sa
    password: 19830415asdfgh
#    password: sa
    driver-class-name: net.sourceforge.jtds.jdbc.Driver

#    url: jdbc:mysql://localhost:3306/shop
#    username: root
#    password: 123456
#    driver-class-name: org.gjt.mm.mysql.Driver




mybatis:
  # mybatis配置
  # 配置映射类所在包名
  type-aliases-package: com.pb.charts.entity.domain
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
      - mapping/*.xml
      - mapping/VO/*.xml

#pagehelper:
#  helperDialect: sqlserver
#  reasonable: true
#  supportMethodsArguments: true



redis:
  #redis配置
  spring.redis.database: 1
  spring.redis.host: 127.0.0.1
  spring.redis.port: 6379
#  spring.redis.password：
  spring.redis.pool.max-idle: 8
  spring.redis.pool.min-idle: 0
  spring.redis.pool.max-active: 8
  spring.redis.pool.max-wait: -1
  spring.redis.timeout: 5000


#配置日志
logging:
  #配置日志文件路径
  level:
    com.pb.charts: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.mybatis: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log